
const config = {
splashScreen: require('./src/assets/AttestationsGold.png'),
primaryColor: '#683c3c',
textColorHeadings: '#2A2A31',
secondaryColor: '#473535',
tertiaryColor: '#5c2929',
logo: require('./src/assets/AttestationsGold.png'),
backgroundImage: require('./src/assets/deleteWhite.png'),
backgroundColorImage: '',
backgroundImageType: 'png',
subLogo:require('./src/assets/bellIcon.png'),
backgroundColor: '#FFFFFF',
modalColor: '#8a5252',
buttonText: '#754949',
headerColor: '#8a3f3f',
BUNDLE_ID: 'sdf.org.easypatient',
Name: 'rew',
ISSUER_ID: "adsasda",
KEY_ID: "adsasd",
private_key: 