# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Deploy Android app to Google Play"
  lane :deploy do
    gradle(
      task: "assemble",
      build_type: "release"
    )
    supply(
      apk: "./app/build/outputs/apk/release/app-release.apk", # Path to your APK
      track: "internal",  # You can set this to 'alpha', 'beta', 'production'
      json_key: "fastlane/easy-patient-a6d4e-60ad241e00ca.json"  # Path to your Google Play service account JSON
    )
  end
end
