# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
    # LANE 1
    desc "Publish a new version to the Google Play (INTERNAL)"
    lane :internal do

        # Generate AAB file
        gradle(
            task: "bundle",
            build_type: "Release"
        )

        # Upload AAB to Play Store (first-time deployment)
        supply(
          aab: "/home/runner/work/Easy-Patient/Easy-Patient/android/app/build/outputs/bundle/release/app-release.aab",
          track: "internal",  # Set this to 'internal', 'alpha', 'beta', 'production'
          skip_upload_metadata: true, # Skip metadata upload for the first time (optional)
          skip_upload_images: true,   # Skip image upload for now (optional)
          skip_upload_screenshots: true, # Skip screenshots upload for now (optional)
          json_key: "fastlane/easy-patient-a6d4e-60ad241e00ca.json", # Path to your JSON key file
          package_name: "com.org.easypatientdynamic" # Your app's package name
        )
    end
end

