name: Android Build and Deploy

on:
  push:
    branches:
      - FixesForiOSBuild

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK version 17 using Temurin distribution
      - name: Set Up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      # Install Node.js and NPM dependencies
      - name: Set up Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install --force

      # Ensure that gradlew has execution permissions
      # - name: Ensure gradlew is executable
      #   run: chmod +x android/gradlew

      # # Build Project to generate .aab file
      # - name: Build AAB
      #   run: |
      #     cd android
      #     ./gradlew bundleRelease

      # # Upload the .aab file as an artifact
      # - name: Upload AAB file as artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: app-release.aab
      #     path: android/app/build/outputs/bundle/release/app-release.aab

      # Declare metadata variables and save them in the environment
      - name: Set metadata variables
        run: |
          echo "APP_TITLE='Your App Title'" >> $GITHUB_ENV
          echo "APP_SHORT_DESCRIPTION='Your short description goes here.'" >> $GITHUB_ENV
          echo "APP_FULL_DESCRIPTION='Your full app description goes here. Provide detailed information about the app.'" >> $GITHUB_ENV
          echo "APP_LANGUAGE='en-US'" >> $GITHUB_ENV
          echo "APP_VERSION_CODE='2'" >> $GITHUB_ENV
          echo "APP_VERSION_NAME='1.1.0'" >> $GITHUB_ENV
          echo "APP_CONTACT_EMAIL='support@example.com'" >> $GITHUB_ENV
          echo "APP_PRIVACY_POLICY_URL='https://your-privacy-policy-url.com'" >> $GITHUB_ENV

      # Set up Fastlane and Bundler for deployment
      - name: Install Fastlane and Bundler
        run: |
          sudo gem install bundler
          sudo gem install fastlane

      # Deploy Android app to Google Play Store using Fastlane
      - name: Deploy Android app to Google Play
        run: |
          cd android
          sudo bundle install
          bundle exec fastlane internal
