name: Android Build

on:
  push:
    branches:
      - FixesForiOSBuild
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Dependencies
        run: npm install --force

      - name: Ensure gradlew is executable
        run: chmod +x android/gradlew

      - name: Build Project
        run: |
          cd android
          ./gradlew assembleRelease
