name: Android Build and Deploy

on:
  push:
    branches:
      - FixesForiOSBuild

jobs:
  upload_screenshots:
    runs-on: ubuntu-latest
    steps:
      # Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK version 17 using Temurin distribution
      - name: Set Up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      # Install Node.js and NPM dependencies
      - name: Set up Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install Dependencies
      - name: Install Dependencies
        run: npm install --force

      # Ensure that gradlew has execution permissions
      - name: Ensure gradlew is executable
        run: chmod +x android/gradlew

      # # Commented Out Build Project to generate .aab file
      # - name: Build AAB
      #   run: |
      #     cd android
      #     ./gradlew bundleRelease

      # # Commented Out Upload the .aab file as an artifact
      # - name: Upload AAB file as artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: app-release.aab
      #     path: android/app/build/outputs/bundle/release/app-release.aab

      # Set up Fastlane and Bundler for deployment
      - name: Install Fastlane and Bundler
        run: |
          sudo gem install bundler
          sudo gem install fastlane

      # Upload Android app screenshots to Google Play using Fastlane
      - name: Upload Screenshots to Google Play
        run: |
          cd android
          sudo bundle install
          fastlane android upload_metadata
