name: Android Screenshots

on:
  push:
    branches:
      - ScreenshotBuild  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK 11 for Android build
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # Step 3: Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2


      # Step 4: Grant execution permissions for Gradle wrapper
      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      # Step 5: Build the APK using Gradle
      # - name: Build APK
      #   run: ./gradlew assembleRelease

      # Step 6: Start the Android Emulator
      - name: Start emulator
        run: |
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd -n test -k "system-images;android-30;default;x86_64"
          nohup $ANDROID_HOME/emulator/emulator -avd test -no-snapshot -no-window -no-audio -gpu swiftshader_indirect &

      # Step 7: Wait for the Emulator to boot
      - name: Wait for emulator
        run: adb wait-for-device

      # Step 8: Install the built APK on the emulator
      - name: Install APK on Emulator
        run: adb install app/build/outputs/apk/release/app-release.apk

      # Step 9: Launch the app on the emulator
      - name: Launch the app
        run: adb shell am start -n "com.easypatientdynamic/com.easypatientdynamic.MainActivity"

      # Step 10: Capture Screenshots
      - name: Capture Screenshots
        run: |
          # Define where to save screenshots
          SCREENSHOT_DIR=$GITHUB_WORKSPACE/screenshots
          mkdir -p $SCREENSHOT_DIR

          # Take screenshots using adb
          adb exec-out screencap -p > $SCREENSHOT_DIR/screenshot1.png
          adb shell input keyevent 82 # Unlock screen if needed
          adb exec-out screencap -p > $SCREENSHOT_DIR/screenshot2.png

      # Step 11: Upload screenshots as artifacts
      - name: Upload Screenshots
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: screenshots/
