name: iOS Screenshot Upload Automation
on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3

      - name: Install dependencies
        run: |
          gem install jwt
          pip install requests

      - name: Generate JWT
        id: generate_jwt
        run: |
          ISSUER_ID="YOUR_ISSUER_ID"
          KEY_ID="YOUR_KEY_ID"
          private_key="
          -----BEGIN PRIVATE KEY-----
          YOUR_PRIVATE_KEY
          -----END PRIVATE KEY-----
          "

          token=$(ruby -rjwt -ropenssl -e "
            private_key_obj = OpenSSL::PKey::EC.new('$private_key')
            token = JWT.encode(
              {
                iss: '$ISSUER_ID',
                exp: Time.now.to_i + 20 * 60,
                aud: 'appstoreconnect-v1'
              },
              private_key_obj,
              'ES256',
              header_fields = {
                kid: '$KEY_ID'
              }
            )
            puts token
          ")
          
          echo "token=$token" >> $GITHUB_ENV

      - name: Calculate image checksum
        id: checksum
        run: |
          file_path="src/assets/Screenshots/04.png"
          checksum=$(shasum -a 256 "$file_path" | awk '{ print $1 }')
          echo "checksum=$checksum" >> $GITHUB_ENV

      - name: Create Screenshot Set
        id: create_screenshot_set
        run: |
          response=$(curl -X POST \
            -H "Authorization: Bearer ${{ secrets.token }}" \
            -H "Content-Type: application/json" \
            -d '{
              "data": {
                "type": "appScreenshotSets",
                "attributes": {
                  "deviceType": "IPHONE_6_5_INCH"
                },
                "relationships": {
                  "appStoreVersion": {
                    "data": {
                      "id": "YOUR_APP_STORE_VERSION_ID",
                      "type": "appStoreVersions"
                    }
                  }
                }
              }
            }' \
            https://api.appstoreconnect.apple.com/v1/appScreenshotSets)

          screenshot_set_id=$(echo $response | jq -r '.data.id')
          echo "screenshot_set_id=$screenshot_set_id" >> $GITHUB_ENV

      - name: Upload Screenshot
        run: |
          response=$(curl -X POST \
            -H "Authorization: Bearer ${{ secrets.token }}" \
            -H "Content-Type: application/json" \
            -d '{
              "data": {
                "type": "appScreenshots",
                "attributes": {
                  "sourceFileChecksum": "${{ env.checksum }}",
                  "uploaded": false
                },
                "relationships": {
                  "appScreenshotSet": {
                    "data": {
                      "id": "${{ env.screenshot_set_id }}",
                      "type": "appScreenshotSets"
                    }
                  }
                }
              }
            }' \
            https://api.appstoreconnect.apple.com/v1/appScreenshots)

          upload_url=$(echo $response | jq -r '.data.attributes.uploadOperations[0].url')
          curl -X PUT \
            -H "Content-Type: image/png" \
            --data-binary "@src/assets/Screenshots/04.png" \
            "$upload_url"

      - name: Finalize Screenshot Upload
        run: |
          screenshot_id=$(echo $response | jq -r '.data.id')
          curl -X PATCH \
            -H "Authorization: Bearer ${{ secrets.token }}" \
            -H "Content-Type: application/json" \
            -d '{
              "data": {
                "id": "'"$screenshot_id"'",
                "type": "appScreenshots",
                "attributes": {
                  "uploaded": true
                }
              }
            }' \
            https://api.appstoreconnect.apple.com/v1/appScreenshots/"$screenshot_id"
