name: iOS Certificate Automation

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Generate Certificate Signing Request (CSR)
        run: |
          openssl genrsa -out private.key 2048
          openssl req -new -key private.key -out csr.certSigningRequest -subj "/emailAddress=${{ secrets.APPLE_ID }}, CN=${{ secrets.CERT_COMMON_NAME }}, C=US"

      - name: Install requests library
        run: pip install requests

      - name: Request Distribution Certificate from Apple Developer API
        env:
          APPLE_API_KEY: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}
          APPLE_API_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APPLE_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
        run: |
          python <<EOF
          import jwt
          import time
          import base64
          import requests

          # Generate JWT token
          private_key = """${{ secrets.APPLE_API_KEY }}"""
          key_id = "${{ secrets.APPLE_API_KEY_ID }}"
          issuer_id = "${{ secrets.APPLE_API_ISSUER_ID }}"

          headers = {
              "alg": "ES256",
              "kid": key_id
          }

          payload = {
              "iss": issuer_id,
              "iat": int(time.time()),
              "exp": int(time.time()) + 1200,
              "aud": "appstoreconnect-v1"
          }

          token = jwt.encode(payload, private_key, algorithm="ES256", headers=headers)

          # Read CSR file
          with open('csr.certSigningRequest', 'rb') as csr_file:
              csr_content = csr_file.read()
          
          # Base64 encode the CSR content
          csr_b64 = base64.b64encode(csr_content).decode('utf-8')

          # API request to create the distribution certificate
          url = "https://api.appstoreconnect.apple.com/v1/certificates"
          headers = {
              "Authorization": f"Bearer {token}",
              "Content-Type": "application/json"
          }
          data = {
              "data": {
                  "type": "certificates",
                  "attributes": {
                      "certificateType": "IOS_DISTRIBUTION",
                      "csrContent": csr_b64
                  }
              }
          }

          response = requests.post(url, json=data, headers=headers)

          if response.status_code == 201:
              cert_content = response.json()['data']['attributes']['certificateContent']
              with open('distribution.cer', 'w') as cert_file:
                  cert_file.write(cert_content)
              print("Distribution Certificate created successfully")
          else:
              print("Failed to create Distribution Certificate")
              print(response.json())
          EOF

      - name: Convert Certificate to .p12 format
        run: |
          openssl x509 -in distribution.cer -inform PEM -outform DER -out distribution.der
          openssl pkcs12 -export -inkey private.key -in distribution.der -out distribution.p12 -name "iOS Distribution" -password pass:${{ secrets.P12_PASSWORD }}

      - name: Upload .p12 file as GitHub Actions artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-distribution-p12
          path: distribution.p12

      - name: Import certificate to keychain for signing
        run: |
          security create-keychain -p "temp_password" build.keychain
          security import distribution.p12 -k build.keychain -P "${{ secrets.P12_PASSWORD }}" -A
          security list-keychains -s build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "temp_password" build.keychain
          security set-keychain-settings build.keychain
          security set-key-partition-list -S apple-tool:,apple: -s -k "temp_password" build.keychain
