name: CI/CD Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3

      - name: Install dependencies (optional)
        run: |
          gem install jwt

      - name: Generate JWT
        id: generate_jwt
        run: |
          ISSUER_ID="ad39d400-3314-48f8-977c-29a272eebad0"
          KEY_ID="74H4QHFPVP"
          private_key="
          -----BEGIN PRIVATE KEY-----
          MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgmtzyTVPL1cphRZjf
          pzIlE/6pV5OFCS6zaUoyqBIHflygCgYIKoZIzj0DAQehRANCAASQxfZ0NyqZre50
          6NGowYahQsvqEQew5MStUc94chxoi8QqtVNTOcsgzqflnQ/v7YeETnnUX+P+2+2E
          +EG+nw8t
          -----END PRIVATE KEY-----
          "

          token=$(ruby -rjwt -ropenssl -e "
            private_key_obj = OpenSSL::PKey::EC.new('$private_key')
            token = JWT.encode(
              {
                iss: '$ISSUER_ID',
                exp: Time.now.to_i + 20 * 60,
                aud: 'appstoreconnect-v1'
              },
              private_key_obj,
              'ES256',
              header_fields = {
                kid: '$KEY_ID'
              }
            )
            puts token
          ")
          
          echo "token=$token" >> $GITHUB_ENV

      - name: Retrieve Devices from App Store Connect
        run: |
          echo "Retrieving Devices..."
          response=$(curl -s -w "%{http_code}" -X GET https://api.appstoreconnect.apple.com/v1/devices \
            -H "Authorization: Bearer ${{ env.token }}" \
            -H "Content-Type: application/json")
          
          # Extract response body and status code
          body=$(echo "$response" | sed -e 's/^[0-9]*$//')
          status_code=$(echo "$response" | tail -n1)
          
          echo "Response Status Code: $status_code"
          echo "Response Body: $body"
          
          if [ "$status_code" -ne 200 ]; then
            echo "Failed to retrieve devices. Status code: $status_code"
            exit 1
          fi
      
          echo "$body" > devices.json
          device_id=$(echo "$body" | jq -r '.data[0].id')
          if [ -z "$device_id" ]; then
            echo "No device ID found in response"
            exit 1
          fi
          echo "device_id=$device_id" >> $GITHUB_ENV
