name: CI/CD for STAGE
'on':
  push:
    branches:
      - development
env:
  BUILD_CERTIFICATE_BASE64: '${{ secrets.BUILD_CERTIFICATE_BASE64 }}'
  P12_PASSWORD: '${{ secrets.P12_PASSWORD }}'
  BUILD_PROVISION_PROFILE_BASE64: '${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}'
  KEYCHAIN_PASSWORD: '${{ secrets.KEYCHAIN_PASSWORD }}'
  APPSTORE_USERNAME: '${{ secrets.APPLEID_USERNAME }}'
  APPSTORE_PASSWORD: '${{ secrets.APPLEID_PASSWORD }}'
  APP_SPECIFIC_PASSWORD: '${{ secrets.APP_SPEC_PASSWORD }}'
  EXPORT_OPTIONS_PLIST: '${{ secrets.EXPORT_OPTIONS_PLIST }}'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          gem install cocoapods

          cd ios
          pod install

          npm install  
