name: Take Screenshots and Upload Artifacts

on:
  push:
    branches:
      - FixesForiOSBuild

jobs:
  take-screenshots:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install puppeteer

      - name: Take screenshots with Puppeteer
        run: |
          node -e "
          const puppeteer = require('puppeteer');
          const fs = require('fs');
          const path = require('path');
          const devices = puppeteer.devices;
          const KnownDevices = puppeteer.KnownDevices;
          const iPhone = KnownDevices['iPhone 14'];

          (async () => {
            const browser = await puppeteer.launch();
            const page = await browser.newPage();
            await page.emulate(iPhone);

            // File paths for local HTML files
            const filePaths = [path.resolve(process.cwd(), 'page1.html')];

            const screenshots = [];

            for (let i = 0; i < filePaths.length; i++) {
              await page.goto(`file://${filePaths[i]}`);
              const screenshotFileName = `screenshot-iphone14-${i + 1}.png`;
              await page.screenshot({ path: screenshotFileName });
              screenshots.push(screenshotFileName);
            }

            await browser.close();

            console.log('Screenshots taken successfully!');
          })();
          "

      - name: Upload screenshots as artifacts
        uses: actions/upload-artifact@v3 # Updated version
        with:
          name: screenshots
          path: |
            screenshot-iphone14-*.png
