name: Take Screenshots and Upload Artifacts

on:
  push:
    branches:
      - ScreenshotAndroid

jobs:
  take_screenshots:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Specify the Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run Puppeteer script
      - name: Run Puppeteer screenshot script
        run: node screenshot-and-create-html.js

      # Step 5: Upload screenshots as artifacts
      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: |
            screenshot-iphone14-1.png
            screenshot-iphone14-2.png
