name: iOS Screenshot Upload
on:
  push:
    branches:
      - ScreenshotBuild
jobs:
  build:
    runs-on: macos-13
    steps:
      - name: List available runtimes
        run: |
          xcrun simctl list runtimes


