name: iOS Screenshot Upload
on:
  push:
    branches:
      - ScreenshotBuild
jobs:
  build:
    runs-on: macos-13
    steps:
      - name: List available runtimes
        run: |
          xcrun simctl list runtimes

      - name: Fetching devices
        run: |
          xcrun simctl list devices

      - name: Create iPhone 8 Simulator
        run: |
          echo "Creating iPhone 8 Simulator..."
          xcrun simctl create "iPhone 8" com.apple.CoreSimulator.SimDeviceType.iPhone-8 com.apple.CoreSimulator.SimRuntime.iOS-17-0
          
          echo "Booting iPhone 8 Simulator..."
          xcrun simctl boot "iPhone 8"

          echo "Verifying boot status..."
          BOOT_STATUS=$(xcrun simctl list | grep -A 1 "iPhone 8" | grep "(Booted)")
          
          if [ -z "$BOOT_STATUS" ]; then
            echo "iPhone 8 Simulator failed to boot."
            exit 1
          else
            echo "iPhone 8 Simulator booted successfully."
          fi



