name: iOS Screenshot Upload
on:
  push:
    branches:
      - ScreenshotBuild
jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Find iOS Simulator UUID
        id: find_simulator2
        run: |
          SIMULATOR_NAME="iPhone 8 Plus" # Changed to the desired simulator name
          UUID=$(xcrun simctl list devices | grep "$SIMULATOR_NAME" | grep "Shutdown" | head -n 1 | awk -F '[()]' '{print $2}')
          echo "Simulator UUID: $UUID"
          echo "SIMULATOR_UUID=$UUID" >> $GITHUB_ENV

      - name: Boot iOS Simulator
        run: |
          xcrun simctl boot ${{ env.SIMULATOR_UUID }}




